version: "3"
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
    hostname: "rabbitmq"

  api:
    build:
      context: ./Api
    ports:
      - 8080:80
      - 443:443
    restart: on-failure
    depends_on:
      - rabbitmq
    

  business:
    build:
      context: ./Business
    restart: on-failure
    depends_on:
      - rabbitmq
      
# networks:
#   host:
#     driver: host